### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by 123kfl** [eleozzr/desc#44]
Hello, author! Do you have a pre trained model and code? Can you share it?
@eleozzr

**Comment by eleozzr** [comment]
You can refer to our tutorial [desc_2.1.1_paul.ipynb](https://eleozzr.github.io/desc/jupyter_notebook/desc_2.1.1_paul.ipynb) for detail.

**Comment by 123kfl** [comment]
Hi! Dear teacher, I read carefully based on your first answer. I also configured the package version in my environment and desc_2.1.1_paul.ipynb according to the package version on desc_2.1.1_paul.ipynb. The same, but I still encountered the same problem as before during training. I tried to solve it for a long time, but it didn't solve it in the end. Now sincerely come to ask you, I hope you can give a solution, because I am very interested in the research in this area, I want to learn the complete reproduction of this code in detail.

**Comment by 123kfl** [comment]
Hi! Dear teacher, I read carefully based on your first answer. I also configured the package version in my environment and desc_2.1.1_paul.ipynb according to the package version on desc_2.1.1_paul.ipynb. The same, but I still encountered the same problem as before during training. I tried to solve it for a long time, but it didn't solve it in the end. Now sincerely come to ask you, I hope you can give a solution, because I am very interested in the research in this area, I want to learn the complete reproduction of this code in detail.
               Traceback (most recent call last):
  File "D:/desc-master/desc/original/train.py", line 317, in <module>
    adata=sc.read("D:\code\desc-master (1)\desc-master\desc\original\data\paul15\paul15.h5")
  File "E:\anaconda\envs\newdesc\lib\site-packages\scanpy\readwrite.py", line 122, in read
    **kwargs,
  File "E:\anaconda\envs\newdesc\lib\site-packages\scanpy\readwrite.py", line 675, in _read
    return read_h5ad(filename, backed=backed)
  File "E:\anaconda\envs\newdesc\lib\site-packages\anndata\_io\h5ad.py", line 429, in read_h5ad
    return AnnData(**d)
TypeError: __init__() got an unexpected keyword argument 'batch.names'

**Comment by 123kfl** [comment]
Hi! Dear teacher, I read carefully based on your first answer. I also configured the package version in my environment and desc_2.1.1_paul.ipynb according to the package version on desc_2.1.1_paul.ipynb. The same, but I still encountered the same problem as before during training. I tried to solve it for a long time, but it didn't solve it in the end. Now sincerely come to ask you, I hope you can give a solution, because I am very interested in the research in this area, I want to learn the complete reproduction of this code in detail.I hope you will reply to me as soon as possible after you see it. I want to learn as soon as possible, thank you!
Traceback (most recent call last):
File "D:/desc-master/desc/original/train.py", line 317, in
adata=sc.read("D:\code\desc-master (1)\desc-master\desc\original\data\paul15\paul15.h5")
File "E:\anaconda\envs\newdesc\lib\site-packages\scanpy\readwrite.py", line 122, in read
**kwargs,
File "E:\anaconda\envs\newdesc\lib\site-packages\scanpy\readwrite.py", line 675, in _read
return read_h5ad(filename, backed=backed)
File "E:\anaconda\envs\newdesc\lib\site-packages\anndata_io\h5ad.py", line 429, in read_h5ad
return AnnData(**d)
TypeError: init() got an unexpected keyword argument 'batch.names'
@eleozzr @Yafei611

**Comment by eleozzr** [comment]
Can you share your code or script. I think the following script works well
```python
#we have downloaded this data, if not, the following will download data automatically
adata=sc.datasets.paul15()
adata.obs['celltype']=adata.obs['paul15_clusters'].str.split("[0-9]{1,2}", n = 1, expand = True).values[:,1]
adata.obs['celltype2']=adata.obs['paul15_clusters']
sc.pp.log1p(adata)
#sc.pp.filter_genes_dispersion(adata,n_top_genes=1000) #older scanpy
sc.pp.highly_variable_genes(adata,n_top_genes=1000,subset=True,inplace=True)
sc.pp.scale(adata,max_value=6)# if the the dataset has two or more batches you can use `adata=desc.scale(adata,groupby="BatchID")`
save_dir="paul_result_2"
adata=desc.train(adata,
        dims=[adata.shape[1],64,32],
        tol=0.005,
        n_neighbors=10,
        batch_size=256,
        louvain_resolution=[0.8,1.0],# not necessarily a list, you can only set one value, like, louvain_resolution=1.0
        save_dir=str(save_dir),
        do_tsne=True,
        learning_rate=200, # the parameter of tsne
        use_GPU=False,
        num_Cores=1, #for reproducible, only use 1 cpu
        num_Cores_tsne=4,
        save_encoder_weights=False,
        save_encoder_step=3,# save_encoder_weights is False, this parameter is not used
        use_ae_weights=False,
        do_umap=False) #if do_uamp is False, it will don't compute umap coordiate
```

**Comment by 123kfl** [comment]
Hello, this is the code I downloaded。
       if __name__=='__main__':
    import argparse
    parser = argparse.ArgumentParser(description='just for simple test train.py',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--use_GPU', default=True, type=bool)
    args = parser.parse_args()
    print(args)
    from load_mnist import load_mnist
    x,y=load_mnist(sample_size=10000,seed=0)
    print ('MNIST use ', x.shape)
    dims=[x.shape[-1],64,32]
    adata=train_single(x,dims,louvain_resolution=0.4,use_GPU=True)
    #adata=train(x,dims,louvain_resolution=[0.2,0.4],use_GPU=False)
    #adata2=train(x,dims,louvain_resolution='0.4,0.6,0.8',use_GPU=args.use_GPU,save_dir='mnist')
    #test for paul15()
    adata=sc.read("D:\code\desc-master\desc-master\desc\original\data\paul15\paul15.h5")
    sc.pp.filter_cells(adata,min_genes=10)
    sc.pp.normalize_per_cell(adata,counts_per_cell_after=1e4)
    sc.pp.log1p(adata)
    sc.pp.filter_genes(adata,min_cells=20)
    #adata=train(adata,louvain_resolution=0.4,use_GPU=True,use_ae_weights=False)
    #adata=train(adata,louvain_resolution="0.2,0.4,0.5",use_GPU=True,use_ae_weights=True,save_encoder_weights=True)
    #adata=train(adata,louvain_resolution='0.5,0.4,0.7',use_GPU=True,use_ae_weights=False,save_encoder_weights=True)

**Comment by 123kfl** [comment]
Hello, this is the code I downloaded at the beginning. I did not understand the part of the code you sent, because I just started learning and I am not too familiar with it. Sincerely ask the teacher for answers, please give me some guidance, thank you !
           I downloaded the code from https://eleozzr.github.io/desc.  @Yafei611 @eleozzr

**Comment by eleozzr** [comment]
I know your problem, you read data using `sc.read("*.h5")`, which is wrong. When you want to read h5 file, you should refer to 
 [https://github.com/theislab/scanpy/blob/9360422823fade22a625f3c7840bef132364027e/scanpy/datasets/_datasets.py#L150-L202](https://github.com/theislab/scanpy/blob/9360422823fade22a625f3c7840bef132364027e/scanpy/datasets/_datasets.py#L150-L202) (line 175-180). I test my following script, it works well. please check your script carefully. 

```python
import numpy as np
import scanpy as sc
#example 1
def load_mnist(sample_size=10000):
    # the data, shuffled and split between train and test sets
    from tensorflow.keras.datasets import mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x = np.concatenate((x_train, x_test))
    y = np.concatenate((y_train, y_test))
    x = x.reshape((x.shape[0], -1))
    print('MNIST samples', x.shape)
    id0 = np.random.choice(x.shape[0], sample_size, replace=False)
    return x[id0], y[id0]

x, y = load_mnist(10000)
dims=[x.shape[-1],64,32]
import desc
adata=desc.train(x,dims,louvain_resolution=1.0,use_GPU=False) #
#esample2 
adata=sc.datasets.paul15() #not read h5 by `sc.read`
sc.pp.filter_cells(adata,min_genes=10)
sc.pp.normalize_per_cell(adata,counts_per_cell_after=1e4)
sc.pp.log1p(adata)
sc.pp.filter_genes(adata,min_cells=20)
adata=train(adata,louvain_resolution=[1.0,1.5],use_GPU=False,use_ae_weights=False,save_encoder_weights=True)
```

**Comment by 123kfl** [comment]
Okay, thank you for your answers. good    @@@luck！
@eleozzr

**Comment by 123kfl** [comment]
Dear teacher, hello! I modified it based on your answer. Although the original error is gone, there are other errors. 
 Traceback (most recent call last):
  File "D:/desc-master/desc/original/train.py", line 342, in <module>
    adata=desc.train(x,dims,louvain_resolution=1.0,use_GPU=False) #
  File "D:\desc-master\desc\models\desc.py", line 333, in train
    kernel_clustering=kernel_clustering)
  File "D:\desc-master\desc\models\desc.py", line 149, in train_single
    kernel_clustering=kernel_clustering
  File "D:\desc-master\desc\models\network.py", line 175, in __init__
    self.pretrain()
  File "D:\desc-master\desc\models\network.py", line 202, in pretrain
    sae.autoencoders.load_weights(os.path.join(self.save_dir,"ae_weights.h5"))
  File "E:\anaconda\envs\newdesc\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "E:\anaconda\envs\newdesc\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1222, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "E:\anaconda\envs\newdesc\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 651, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
Can the teacher give me a new and complete code? My original code was downloaded from GitHub and you uploaded the code, but I always changed one error and then another error occurred, so can I trouble the teacher to upload a new one? Code, so that I can devote myself to learning as soon as possible, thank you!
@eleozzr @Yafei611

**Comment by eleozzr** [comment]
I have already given the complete script!!!!!! I do not know why you still use your code.
```python
import numpy as np
import scanpy as sc
#example 1
def load_mnist(sample_size=10000):
    # the data, shuffled and split between train and test sets
    from tensorflow.keras.datasets import mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x = np.concatenate((x_train, x_test))
    y = np.concatenate((y_train, y_test))
    x = x.reshape((x.shape[0], -1))
    print('MNIST samples', x.shape)
    id0 = np.random.choice(x.shape[0], sample_size, replace=False)
    return x[id0], y[id0]

x, y = load_mnist(10000)
dims=[x.shape[-1],64,32]
import desc
adata=desc.train(x,dims,louvain_resolution=1.0,use_GPU=False) #you can set  `use_ae_weights=False`, when you run this code twice with different dims.
#esample2 
adata=sc.datasets.paul15() #not read h5 by `sc.read`
sc.pp.filter_cells(adata,min_genes=10)
sc.pp.normalize_per_cell(adata,counts_per_cell_after=1e4)
sc.pp.log1p(adata)
sc.pp.filter_genes(adata,min_cells=20)
adata=train(adata,louvain_resolution=[1.0,1.5],use_GPU=False,use_ae_weights=False,save_encoder_weights=True)
```

**Comment by 123kfl** [comment]
I'm sorry, teacher, I might not be able to use this aspect when I first came into contact with it. Let me take a look at the revision, thank you for your hard work! @eleozzr

**Comment by 123kfl** [comment]
Dear author, hello! I ran according to the script I gave and ran out four pictures, but the four pictures did not match the pictures in the paper, and the training and testing parts were able to run successfully, but the pictures couldn’t come out, so I solved it myself. , But it didn't come out. I also trouble the author to give patience and guidance. Now I have succeeded with just one picture. I hope you can restore it as soon as possible. Thank you very much!
 
![Figure_1](https://user-images.githubusercontent.com/90680667/134333148-47f14e49-4595-4b18-ac2b-6624c8cd2a1c.png)
![Figure_2](https://user-images.githubusercontent.com/90680667/134333274-87d2d055-26c5-47ff-a721-a24f7685bec9.png)
 @eleozzr @Yafei611

**Comment by 123kfl** [comment]
Hello, dear author! I want to know, is the data set of the code you uploaded and the data set in the script you gave the same? The picture I ran out is a bit different from the code you gave on GitHub, and the code you gave on GitHub is different from your script. I wonder if you have the latest version that matches your script. Code, because the current code runs too many errors and needs to be constantly changed. The final result is different from your reproduced one. I have this question, and I would like to trouble you to answer it. I hope the teacher will not dislike it, answer my questions patiently and give guidance, thank you very much! ! !
@eleozzr @Yafei611

**Comment by 123kfl** [comment]
Hello, dear author! I reproduced the clustering result in desc_2.1.1_paul.ipynb according to the script you gave, but it is different from the picture result in your paper. I want to know whether the data set in your paper and the data set in your code same? Also, the code you uploaded on GitHub is different from the new script you gave. Is this because your code has not been updated? These are my current two questions. I sincerely hope that the author and friends can answer my questions. I come to ask you for advice and study with a sincere heart. Please give me some guidance, thank you very much!
![Figure_1](https://user-images.githubusercontent.com/90680667/134468969-3acf4a54-44e1-4378-99f0-0d2d50220b3d.png)
![Figure_2](https://user-images.githubusercontent.com/90680667/134469056-583c0cfb-f753-415c-82b3-83a85913606a.png)
@eleozzr @Yafei611

**Comment by eleozzr** [comment]
> Hello, dear author! I reproduced the clustering result in desc_2.1.1_paul.ipynb according to the script you gave, but it is different from the picture result in your paper. I want to know whether the data set in your paper and the data set in your code same? Also, the code you uploaded on GitHub is different from the new script you gave. Is this because your code has not been updated? These are my current two questions. I sincerely hope that the author and friends can answer my questions. I come to ask you for advice and study with a sincere heart. Please give me some guidance, thank you very much!
> ![Figure_1](https://user-images.githubusercontent.com/90680667/134468969-3acf4a54-44e1-4378-99f0-0d2d50220b3d.png)
> ![Figure_2](https://user-images.githubusercontent.com/90680667/134469056-583c0cfb-f753-415c-82b3-83a85913606a.png)
> @eleozzr @Yafei611

Firstly, I provided you my reproducing code but you missed it (four days ago). For the second reply, I simply provide an example code but not for the paul dataset (just use `sc.datasets.paul15()`  to tell you how to read data).  The reason why the result is different from that in our paper is that using different versions of TensorFlow.  [desc_2.1.1_paul.ipynb](https://eleozzr.github.io/desc/jupyter_notebook/desc_2.1.1_paul.ipynb) used tensorflow2.* and [desc_2.0.3_paul.ipynb](https://eleozzr.github.io/desc/jupyter_notebook/desc_2.0.3_paul.ipynb) used tensorflow1.* 

Please read our tutorial carefully before asking questions. Thanks.

**Comment by 123kfl** [comment]
Hi! I used tensorflow2.1.0 and desc_2.1.1_paul.ipynb, but the results that I ran were different from yours, and the pictures could not be displayed after the code was run. These two pictures still use the desc_2.1.1_paul.ipynb you mentioned. I ran out alone, and other codes have no pictures, so I am a little confused about this now, I hope you can answer, don’t dislike my trouble, because I have also modified and consulted others, but I have not solved it, there is no way I just came to ask you, please teacher! Can you also ask which data set is used in your paper? Secondly, the code you copied to me seems to be only part of it. What I want to ask is the complete new code like on GitHub. desc_2.1.1_paul.ipynb seems to be just a pre-trained model. Please don’t dislike my problem. Please understand, thank you! !Please understand, thank you! ! I hope the teacher can reply in time and disturb you.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eleozzr/desc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午4:24
***@***.***&gt;;
抄送:&nbsp;"( •͈ᴗ⁃͈)ᓂ- - ***@***.******@***.***&gt;;
主题:&nbsp;Re: [eleozzr/desc] consult (#44)





  
Hello, dear author! I reproduced the clustering result in desc_2.1.1_paul.ipynb according to the script you gave, but it is different from the picture result in your paper. I want to know whether the data set in your paper and the data set in your code same? Also, the code you uploaded on GitHub is different from the new script you gave. Is this because your code has not been updated? These are my current two questions. I sincerely hope that the author and friends can answer my questions. I come to ask you for advice and study with a sincere heart. Please give me some guidance, thank you very much!
 
 
 @eleozzr @Yafei611
  
Firstly, I provided you my reproducing code but you missed it (four days ago). For the second reply, I simply provide an example code but not for the paul dataset (just use sc.datasets.paul15()  to tell you how to read data).  The reason why the result is different from that in our paper is that using different versions of TensorFlow.  desc_2.1.1_paul.ipynb used tensorflow2.* and desc_2.0.3_paul.ipynb used tensorflow1.*
 
Please read our tutorial carefully before asking questions. Thanks.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123kfl** [comment]
Hello! Could you explain the functions corresponding to the programs that run the script? Thank you very much! ! !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eleozzr/desc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午4:24
***@***.***&gt;;
抄送:&nbsp;"( •͈ᴗ⁃͈)ᓂ- - ***@***.******@***.***&gt;;
主题:&nbsp;Re: [eleozzr/desc] consult (#44)





  
Hello, dear author! I reproduced the clustering result in desc_2.1.1_paul.ipynb according to the script you gave, but it is different from the picture result in your paper. I want to know whether the data set in your paper and the data set in your code same? Also, the code you uploaded on GitHub is different from the new script you gave. Is this because your code has not been updated? These are my current two questions. I sincerely hope that the author and friends can answer my questions. I come to ask you for advice and study with a sincere heart. Please give me some guidance, thank you very much!
 
 
 @eleozzr @Yafei611
  
Firstly, I provided you my reproducing code but you missed it (four days ago). For the second reply, I simply provide an example code but not for the paul dataset (just use sc.datasets.paul15()  to tell you how to read data).  The reason why the result is different from that in our paper is that using different versions of TensorFlow.  desc_2.1.1_paul.ipynb used tensorflow2.* and desc_2.0.3_paul.ipynb used tensorflow1.*
 
Please read our tutorial carefully before asking questions. Thanks.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
