### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by kongfengling** [eleozzr/desc#45]
Dear teacher, hello! I have successfully reproduced your code, but I used my own data set to run your code. The data set cannot be read. The error message is that the format of my data set is different from yours and cannot be read. But I don’t know the specific style of your Paul5 data set, and I can’t download Paul15 on the Internet, so the processing format of my own data set is different from yours, so that it reports an error, so now I can ask if you can Share your Paul5 data set. I want to change my own data according to your data set format, and see if my data can run according to your changes. Teacher, I’m sincerely to ask for advice. I hope the teacher can reply to my request. Thank you very much. Good luck.
@eleozzr @Yafei611

**Comment by eleozzr** [comment]
Please refer to 
https://www.jianguoyun.com/p/DTRqbsoQw4OhBxjCsJIE (access passwd: nbMRit)

**Comment by kongfengling** [comment]
thank you very much!
